title: BCIA 38
email: info@lilotbad.fr
toplogo: logo.png
description: >- # this means to ignore newlines until "baseurl:"
  Pratique de bad pour tous niveaux à l'Isle d'Abeau
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bcia.lilotbad.fr" # the base hostname & protocol for your site, e.g. http://example.com
default_locale: "fr"
google_analytics_id: #UA-XXXX-Y
google_maps_javascript_api_key: "YOUR_GOOGLE_MAPS_API_KEY"

# Build settings
show_excerpts: true
excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  #- jekyll-google-calendar

exclude:
  - README.md
  - CODE_OF_CONDUCT.md

collections:
  - members
  - teams

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "member"
    values:
      layout: "member"
  - scope:
      path: ""
      type: "teams"
    values:
      layout: "team"
  - scope:
      path: ""
      type: "lilotbad"
    values:
      layout: "lilotbad"
  - scope:
      path: ""
    values:
      layout: "default"
