title: BCIA 38
description: >- # this means to ignore newlines until "baseurl:"
  Pratique de bad pour tous niveaux à l'Isle d'Abeau
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bcia.lilotbad.fr" # the base hostname & protocol for your site, e.g. http://example.com

timezone: Europe/Paris
profile: true
#livereload: true #doesn't work on Windows...

# Build settings
show_excerpts: true
excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  #- jekyll-google-calendar

exclude:
  - README.md
  - CODE_OF_CONDUCT.md

collections:
  interclubs:
    output: true
    variable: test

defaults:
  - scope:
      path: ""
      type: "interclubs"
    values:
      layout: "common"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "lilotbad"
    values:
      layout: "lilotbad"
  - scope:
      path: "lilotdouble"
    values:
      layout: "lilotdouble"
  - scope:
      path: ""
    values:
      layout: "common"
